spring:
  application:
    name: springsecuritybasic
#  security:
#    user:
#      name: user
#      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?useServerPrepstmts=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root123123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true